---
- name: check the binaries checksum 
  stat: 
    path: "{{ gaiad_binary_location }}"
    checksum_algorithm: sha256
    get_checksum: yes
  register: sha_stat
  tags: checksums, binaries

- name: copy gaiad v5.0.2 to /usr/local/bin 
  ansible.builtin.copy:
    src: /tmp/gaiad-v5.0.2-linux-amd64
    dest: "{{ gaiad_binary_location }}"
    owner: gaia
    group: gaia
    mode: '0755'
    remote_src: yes 
  when: 
    - sha_stat.stat.checksum != 'b528aff8b9e76c91b76b1288cdc15d13fed6b868d8ff3b74460ea2061bacea9b' 
    - "services_state.ansible_facts.services['gaiad.service'].state != 'running'"
  tags: checksums, binaries