- name: Show facts available on the system
  ansible.builtin.debug:
    var: ansible_facts
    
- name: Create the gaia group
  group:
    name: "{{ _gaia_validator_system_group }}"
    state: present
    system: true
  when: _gaia_validator_system_group != "root"

- name: Create the gaia user
  user:
    name: "{{ _gaia_validator_system_user }}"
    group: "{{ _gaia_validator_system_group }}"
    shell: /usr/sbin/nologin
    create_home: true
    home: /home/gaia
  when: _gaia_validator_system_user != "root"


- name: create gaiad data directory
  file:
    path: "{{ GAIA_HOME }}/gaia"
    state: directory
    owner: gaia
    group: gaia
    mode: 0744
- name: fetch gaiad-v4.2.0 release notes to get checksums
  get_url:
    url: https://github.com/cosmos/gaia/releases/download/v4.2.0/build_report
    dest: /tmp/checksums_v4.2.0
- name: parse the release notes for checksums
  shell: grep linux-amd64 /tmp/checksums_v4.2.0 | sed '/^$/d' | sed -r 's/gaiad-v4.2.0-linux-amd64//g' | tail -n 1
  register: checksum
  tags: checksums
- name: fetch gaiad-v4.2.0 binaries from github to /usr/local/bin
  get_url:
    url: https://github.com/cosmos/gaia/releases/download/v4.2.0/gaiad-v4.2.0-linux-amd64
    dest: "/usr/local/bin/gaiad"
    owner: gaia
    group: gaia
    mode: u+rwx
    checksum: "sha256: {{ checksum.stdout }}"
  #failed_when: checksum = "b528aff8b9e76c91b76b1288cdc15d13fed6b868d8ff3b74460ea2061bacea9b"
  register: _download_binary
  until: _download_binary is succeeded
  retries: 5
  delay: 2
  check_mode: false
  tags: download_old_bin
- name: fetch gaiad-v5.0.2 release notes to get checksums
  get_url:
    url: https://github.com/cosmos/gaia/releases/download/v5.0.2/build_report
    dest: /tmp/checksums_v5.0.2
- name: parse the release notes for checksums
  shell: grep linux-amd64 /tmp/checksums_v5.0.2 | sed '/^$/d' | sed -r 's/gaiad-v5.0.2-linux-amd64//g' | tail -n 1
  register: checksum2
  tags: checksums
- name: fetch gaiad-v5.0.2 binaries from github to /tmp/
  get_url:
    url: https://github.com/cosmos/gaia/releases/download/v5.0.2/gaiad-v5.0.2-linux-amd64
    dest: /tmp/
    owner: gaia
    group: gaia
    mode: u+rwx
    checksum: "sha256: {{ checksum2.stdout }}"
  register: _download_binary
  until: _download_binary is succeeded
  retries: 5
  delay: 2
  check_mode: false 
