---
- name: install service script
  copy:
    src: templates/gaiad.service.j2
    dest: /etc/systemd/system/gaiad.service
    owner: root
    group: root
    mode: u+rwx
  tags: init
- name: enable gaiad.service
  systemd:
    name: gaiad
    enabled: true
  tags: init
- name: reload gaiad.service
  systemd:
    name: gaiad
    daemon_reload: true
  tags: init
- name: start gaiad
  systemd:
    name: gaiad
    state: started
- name: Write down the address and mnemonic
  debug:
    msg: "{{ admin_mnemonic.stdout_lines }}"