---
- name: copy umeed-height.py to /usr/local/lib/ 
  ansible.builtin.copy:
    src: files/umeed-height.py
    dest: "{{ umee_log_path }}/umeed-height.py"
    owner: umee
    group: umee
    mode: '0755'
- name: install service script
  copy:
    src: templates/umee-log.service.j2
    dest: /etc/systemd/system/umee-log.service
    owner: root
    group: root
    mode: u+rwx
- name: enable umee-log.service
  systemd:
    name: umeed
    enabled: true
- name: reload umee-log.service
  systemd:
    name: umee-log
    daemon_reload: true
- name: start umee-log.service
  systemd:
    name: umee-log
    state: started
  tags: logging_restart